### ISSUE TITLE
Question how to use

### ISSUE THREAD

**Issue by johnnykoo84** [MatthieuLemoine/react-grid-path#1]
Hi, Thanks a lot for sharing good react source. 
I'd like to use it, but stuck on how to. Could i get some help? 
your example code is using libraries with relative directories. As far as i understand, I should be able to use the npm library 'react-grid-path' right? 

e.g. import { Grid, Container, Actions } from 'react-grid-path';

Am i on the right track? or Actions are something that I should create for my own action?

Thank you,
Br, Johnny
*I was not sure if I could post this question here in issues page, if not appropriate, please let me know.

**Comment by MatthieuLemoine** [comment]
Hi !

The only component exported by `react-grid-path` is the component named `Grid` in the example app. It's the default export. To use it you just need to add the following import :

```javascript
import Grid from 'react-grid-path'
```

See the README example (It should be 'react-grid-path' instead of 'grid').

`Actions` and `Container` are just part of the example app not the lib.
